### ISSUE TITLE
still leaves copilot enabled within edge sidebar

### ISSUE THREAD

**Issue by TopherBrowne** [zoicware/RemoveWindowsAI#1]
script functions without error on multiple stations... 

however the ms edge sidebar still shows the copilot icon at the top of the sidebar.

![image](https://github.com/zoicware/RemoveWindowsAI/assets/48744446/e5944253-f8ee-4bc2-b5c8-2dde014ea05d)

this can be disabled using edge settings -> sidebar -> app and notification settings...

![image](https://github.com/zoicware/RemoveWindowsAI/assets/48744446/63005a16-e989-4703-81f2-551a43315e21)

![image](https://github.com/zoicware/RemoveWindowsAI/assets/48744446/90eb8d97-9099-4043-8823-cd489ea2b5e8)

can this edge setting be programmatically set at the HKLM level as well as HKCU level?

**Comment by TopherBrowne** [comment]
sidebar after disabling copilot...

![image](https://github.com/zoicware/RemoveWindowsAI/assets/48744446/108b119f-0bb9-4249-a62f-447a100900df)

**Comment by zoicware** [comment]
Thanks added edge policies you can find all of them here https://learn.microsoft.com/en-us/deployedge/microsoft-edge-policies
